const songTones = {
  "Akademisk bordvers": ["C3", "A3"],
  "Ångbåtssång": ["D3", "G3", "A3"],
  "Aquaviten": ["G3", "B3", "D4"],
  "Astri, mi Astri": ["G3", "D3", "A3", "D4"],
  "Boar's Head Carol": ["D3", "G3"],
  "Brudefærden i Hardanger": ["A2", "E3", "A3", "C4"],
  "Busen og småguten": ["G2", "D3"],
  "C'e un passo alpino (San Bernardino)": ["F3"],
  "Champagnegaloppen": ["C4", "E4", "G3"],
  "Den norske Sjømand": ["E3", "A3"],
  "Drikkevise": ["C3"],
  "Dæ æ so fagert i Finneslotte": ["A2", "B2"],
  "Ein König (Das Königslied)": ["A3", "D3"],
  "En øl i handa": ["D3", "G3", "A3"],
  "Fanfare, hymne og fanfare": ["G3"],
  "Far Over The Misty Mountains Cold": ["B2", "B3", "F4", "F2", "A2", "B2"],
  "Finsk snapsvise": ["G3"],
  "Fredmans epistel nr. 13: Nå ä nu alla församlade här": ["F3", "A3", "A3", "F4"],
  "Fredmans epistel nr. 27: Gubben är gammal": ["D3", "F3", "A3", "D4"],
  "Fredmans epistel nr. 30: Drick ur ditt glas": ["F3"],
  "Fredmans epistel nr. 72: Glimmande nymf": ["C3", "E3", "G3", "C4"],
  "Fredmans epistel nr. 9: Käraste bröder": ["A3"],
  "Friseglarens sång": ["B3"],
  "Fyld pokalen (Tourdion)": ["E3", "G3", "B3", "E4"],
  "Gambrinus-visen (Vårt øl)": ["G3"],
  "Gammelt øl": ["A3"],
  "Gaudeamus igitur": ["D3", "G3", "A3", "D4"],
  "Gloucestershire Wassail": ["D3", "G3"],
  "Gryning vid havet": ["B3", "E3"],
  "Halvan": ["D3", "G3"],
  "Hej, dunkom": ["G3", "B3", "D4", "G4"],
  "Helan går": ["A3", "C4", "F3"],
  "Heyr, himna smiður": ["D3", "F3", "A3", "D4"],
  "Hiiden orjien laulu": ["F3"],
  "Irish Blessing": ["C3"],
  "Ja, vi elsker dette landet": ["A3"],
  "Jag vet en dejlig rosa": ["G2", "G3", "H3", "D4"],
  "Jubileumskantate": ["F3"],
  "Kierlighed og Smørrebrød": ["A3"],
  "Kjerringa med staven": ["G3"],
  "Kristallen den fina": ["A3"],
  "Kung Liljekonvalje": ["A2"],
  "Kvarten": ["C3"],
  "Kvinten": ["C3"],
  "Linden Lea": ["F2", "F3"],
  "Lovsang til politiet": ["A3"],
  "Madrigal (Kom, du ljuva hjärtevän)": ["C3", "F3", "G3", "C4"],
  "Masurka (Jentelokken)": ["E3", "B3", "E4", "E5"],
  "Metsämiehen juomalaulu": ["A3"],
  "My Evaline": ["E3", "F3", "G3", "A3"],
  "Naar Fjordene blaaner": ["G3", "B3", "D4"],
  "Norges Fjelde": ["F3"],
  "Norges Skaal": ["D3", "Faharp3", "A3"],
  "Nu klinger": ["D3", "G3"],
  "Olav Trygvason": ["C4"],
  "Oppkomst og nedkomst": ["C3"],
  "Pål sine hønur": ["A2", "F3", "F3", "A3"],
  "Punschens visa": ["C4", "C3"],
  "Rocky Road to Dublin": ["A3"],
  "Ronja Rövardotter": ["F3", "C4", "F4"],
  "Sangerhilsen": ["A3"],
  "Sit on My Face": ["C4", "D4", "E4"],
  "Skjenkarsveinen": ["A2", "F3", "A3", "D4"],
  "Slutkör": ["C3", "E3", "G3", "C4"],
  "Spillopper og flisespikkeri": ["G3"],
  "Studentsång (Sjungom studentens lyckliga dag)": ["G2", "D3", "G3", "B3"],
  "Tantsulaul": ["D3", "A3", "D4"],
  "Tersen": ["D4"],
  "Till Österland": ["F3"],
  "Vackra kvarten": ["A2", "F3", "A3", "D4"],
  "Vals": ["F3", "A3", "D4", "C4"],
  "Vi har vår egen lille verden": ["E3", "A3"],
};
